# Generated by Django 5.1.2 on 2025-02-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0030_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_approve',
            field=models.BooleanField(default=0),
        ),
        migrations.DeleteModel(
            name='Order_approve',
        ),
    ]
