# Generated by Django 5.1.2 on 2025-02-01 07:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0008_alter_newadtype_agency'),
        ('customer', '0031_order_is_approve_delete_order_approve'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.CharField(max_length=255)),
                ('isactive', models.BooleanField(default=True)),
                ('approved', models.BooleanField(default=False)),
                ('isBlocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateField(verbose_name=datetime.date.today)),
            ],
            options={
                'db_table': 'Agency',
            },
        ),
        migrations.RemoveField(
            model_name='agencyprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='adType',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='agency.newadtype'),
        ),
        migrations.AddField(
            model_name='payment',
            name='adType',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='agency.newadtype'),
        ),
        migrations.AddField(
            model_name='agencyprofile',
            name='agency',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='customer.agency'),
        ),
        migrations.AlterField(
            model_name='order',
            name='agency',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='customer.agency'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='agency',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='customer.agency'),
        ),
    ]
