# Generated by Django 5.1.2 on 2025-02-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0032_agency_remove_agencyprofile_user_order_adtype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='password',
            field=models.CharField(default='default_password', max_length=255),
        ),
    ]
