# Generated by Django 5.1.2 on 2025-02-01 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0009_alter_newadtype_agency'),
        ('customer', '0033_agency_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='adType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.newadtype'),
        ),
    ]
