# Generated by Django 5.1.2 on 2025-02-04 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0036_adcategory'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adcategory',
            table='AdCategory',
        ),
    ]
