# Generated by Django 5.1.2 on 2025-02-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0037_alter_adcategory_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='adcategory',
            name='type',
            field=models.CharField(default='Classified Text Ad', max_length=255),
        ),
    ]
