# Generated by Django 5.1.2 on 2025-02-10 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0038_adcategory_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adcategory',
            old_name='type',
            new_name='classifiedtype',
        ),
    ]
