# Generated by Django 5.1.2 on 2025-02-12 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0042_agencyregion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgencyRegion',
        ),
    ]
