# Generated by Django 5.1.2 on 2025-02-12 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0043_delete_agencyregion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.agency')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.city')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.state')),
            ],
            options={
                'db_table': 'agencyregion',
            },
        ),
    ]
