# Generated by Django 5.1.2 on 2025-02-22 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0044_agencyregion'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyprofile',
            name='circulation',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agencyprofile',
            name='per_word_rate',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='agencyprofile',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='customer.city'),
        ),
        migrations.AlterField(
            model_name='agencyprofile',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='customer.state'),
        ),
    ]
