# Generated by Django 5.1.2 on 2025-02-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0045_agencyprofile_circulation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyprofile',
            name='profile_picture',
            field=models.TextField(default='image.jpg'),
        ),
    ]
