# Generated by Django 5.1.2 on 2025-02-26 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0046_agencyprofile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='adType',
        ),
    ]
