# Generated by Django 5.1.2 on 2025-03-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0049_remove_order_size_order_height_order_width_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ad_color',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='any_preferance',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='order',
            name='is_printed',
            field=models.BooleanField(default=0),
        ),
    ]
