# Generated by Django 5.1.2 on 2025-03-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0050_order_ad_color_order_any_preferance_order_is_printed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
