# Generated by Django 5.1.2 on 2025-03-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0052_alter_order_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='any_preferance',
            field=models.TextField(default=None, null=True),
        ),
    ]
