# Generated by Django 5.1.2 on 2025-04-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0055_forgetpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_feedback',
            name='rating',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
