# Generated by Django 5.1.2 on 2025-04-02 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0058_adcategory_is_deleted_addtocart_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Addtocart',
        ),
    ]
