# Generated by Django 5.1.2 on 2025-04-02 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0059_delete_addtocart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Passwordall',
        ),
    ]
