# Generated by Django 5.2 on 2025-04-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0061_agencyinquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyprofile',
            name='adhare_number',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agencyprofile',
            name='adhare_photo',
            field=models.TextField(default='adhare.jpg'),
        ),
        migrations.AddField(
            model_name='agencyprofile',
            name='client_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='agencyprofile',
            name='gst_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='agencyprofile',
            name='pan_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='agencyprofile',
            name='pan_photo',
            field=models.TextField(default='pan.jpg'),
        ),
    ]
