# Generated by Django 5.2 on 2025-04-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0062_agencyprofile_adhare_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='is_recomanded',
            field=models.BooleanField(default=False),
        ),
    ]
