# Generated by Django 5.2 on 2025-04-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0065_orderfeedback_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgetPasswordAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, null=True)),
                ('username', models.CharField(max_length=150, null=True)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('expiry_date_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'forget_password_agency',
            },
        ),
    ]
