# Generated by Django 5.2 on 2025-04-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0066_forgetpasswordagency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='adType',
        ),
        migrations.AddField(
            model_name='payment',
            name='is_payment',
            field=models.BooleanField(default=False),
        ),
    ]
