# Generated by Django 5.2 on 2025-04-20 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0067_remove_payment_adtype_payment_is_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='order_id',
            new_name='order',
        ),
    ]
