# Generated by Django 5.1.2 on 2025-02-01 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0008_alter_newadtype_agency'),
        ('customer', '0032_agency_remove_agencyprofile_user_order_adtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newadtype',
            name='agency',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='customer.agency'),
        ),
    ]
